
services:
  django: 
    image: dattarahegaonkar09/django-app
    container_name: django-app
    ports:
      - "8000:8000"
    networks:
      - django-app

networks:
  django-app:
    external: true